version: '3.9'
services:

  manager_api:
    container_name: django_manager_api
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    volumes:
      - ./manager/.:/app
    ports:
      - 8001:8001
    environment:
      - PORT=8001
    depends_on:
      - manager_db

  manager_db:
    container_name: django_manager_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: django_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./manager/.dbdata:/var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - 3307
