version: '3.9'
services:

  manager_api_local:
    container_name: djmanager_api_local
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    ports:
      - 8001:8000
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    volumes:
      - local-static-data:/vol/app
    depends_on:
      - manager_db

  manager_db_local:
    container_name: djmanager_db_local
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: django_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    volumes:
      - local-mysql-data:/var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - 3307

volumes:
  local-static-data:
  local-mysql-data:
